[tool.poetry]
name = "pythonmonkey"
version = "0" # automatically set by poetry-dynamic-versioning
description = ""
authors = ["Caleb Aikens <caleb@distributive.network>", "Tom Tang <xmader@distributive.network>", "Wes Garland <wes@distributive.network>", "Hamada Gasmallah <hamada@distributive.network>"]
readme = "README.md"
packages = [
  { include = "pythonmonkey", from = "python" },
]
include = [
  # Linux and macOS
  "python/pythonmonkey/pythonmonkey.so",
  "python/pythonmonkey/libmozjs*",
  "python/pythonmonkey/builtin_modules/**/*",

  # Windows
  "python/pythonmonkey/pythonmonkey.pyd",
  "python/pythonmonkey/mozjs-*.dll",

  # include all files for source distribution
  { path = "src", format = "sdist" },
  { path = "include", format = "sdist" },
  { path = "cmake", format = "sdist" },
  { path = "docs", format = "sdist" }, # TODO: organize files
  { path = "externals", format = "sdist" },
  { path = "format", format = "sdist" },
  { path = "tests", format = "sdist" },
  { path = "CMakeLists.txt", format = "sdist" },
  { path = "*.sh", format = "sdist" },
]


[tool.poetry.dependencies]
python = "^3.8"


[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"
bump = true


[tool.poetry.build]
script = "build.py"
generate-setup-file = false 

[tool.poetry.scripts]
pmjs = "pythonmonkey.cli.pmjs:main"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pip = "^23.1.2"
numpy = [
  # numpy hasn't released for Python 3.12 yet on PyPI, but Anaconda nightly build has it.
  # TODO: use the PyPI build once the wheels are released for Python 3.12
  {version = "^2.0.0.dev0", allow-prereleases = true, source = "anaconda-nightly", python = "3.12.*"},
  {version = "^1.24.3", python = "<3.12"},
]


[[tool.poetry.source]]
name = "anaconda-nightly"
url = "https://pypi.anaconda.org/scientific-python-nightly-wheels/simple"
priority = "explicit"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"
